name: Manual build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for skopeo binary'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build skopeo
        id: build_skopeo
        run: |
          set -eux
          # golang:1.22-alpine
          build_image="golang:1.22-alpine"
          docker pull "${build_image}"
          docker run --rm -t -v $PWD:/build -w /build  "${build_image}" sh build-binary.sh
          ls -al bin/
          cd ../
          ls -al ./
          cat ./skopeo/bin/skopeo-{darwin,linux}-{amd64,arm64}.{md5,sha256} > CHECKSUMS.txt
          cat ./skopeo/bin/skopeo-linux-ppc64le.{md5,sha256} >> CHECKSUMS.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ inputs.tags }}-nightly"
          files: |
            ./skopeo/bin/skopeo-linux-amd64
            ./skopeo/bin/skopeo-linux-amd64.md5
            ./skopeo/bin/skopeo-linux-amd64.sha256
            ./skopeo/bin/skopeo-linux-arm64
            ./skopeo/bin/skopeo-linux-arm64.md5
            ./skopeo/bin/skopeo-linux-arm64.sha256
            ./skopeo/bin/skopeo-linux-ppc64le
            ./skopeo/bin/skopeo-linux-ppc64le.md5
            ./skopeo/bin/skopeo-linux-ppc64le.sha256
            ./skopeo/bin/skopeo-darwin-amd64
            ./skopeo/bin/skopeo-darwin-amd64.md5
            ./skopeo/bin/skopeo-darwin-amd64.sha256
            ./skopeo/bin/skopeo-darwin-arm64
            ./skopeo/bin/skopeo-darwin-arm64.md5
            ./skopeo/bin/skopeo-darwin-arm64.sha256
          body_path: ./CHECKSUMS.txt